### PR TITLE
GP2-570 Add header to storybook

### PR DESCRIPTION
**Pull request by bobmeredith**
To do (delete all that do not apply):

 - [x] CSS have been compiled.
 - [x] Add a printscreen to the PR

### CODE REVIEW

**Comment by bobmeredith** [comment]
image

**Review by dahfool — APPROVED** [review]

**Comment by dahfool** [comment]
@bobmeredith all good, do we need a version showing the menu toggled(opened).

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
image

**Comment by bobmeredith** [comment]
image

**Review by dahfool — APPROVED** [review]

**Review by dahfool — APPROVED** [review]

**Pull request merged**
